name: Link Snitch

on:
  push:
    branches:
      - main

env:
  URL: https://filefighter.github.io
  config: .github/linkSnitch-config.json

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Check out master
        uses: actions/checkout@master
      - name: Report broken links
        uses: victoriadrake/link-snitch@master
